In [ ]:
print("Hello World")

In [ ]:
"""
  sample Comments
"""

In [ ]:
#Single Line Comment

#Strings

In [1]:
s = "AUST"
print((s))
print(type(s))
print (s.lower())
print (s[3])

AUST
<class 'str'>
aust
T


In [2]:
s[4]='B'

TypeError: ignored

#Lists

In [3]:
cse_4_2 = [1, 2, 3, 4]
print(cse_4_2)
print(type(cse_4_2))

[1, 2, 3, 4]
<class 'list'>


#Numpy:
NumPy is a popular library for numerical computing in Python, and it provides many useful operations for manipulating arrays and performing mathematical calculations. Here are some common NumPy operations:

##1. Importing numpy

In [5]:
import numpy as np 


##2. Creating arrays: NumPy arrays can be created using the `numpy.array()` function, which takes a list or tuple as input. For example, to create an array of zeros with three elements, you can use the following code: 

In [6]:
arr = np.zeros(3)
brr = np.ones(3)

In [7]:
arr

array([0., 0., 0.])

In [8]:
brr

array([1., 1., 1.])

##3. Basic array operations: NumPy arrays support basic mathematical operations, such as addition, subtraction, multiplication, and division. These operations are performed element-wise, so the arrays must have the same shape. For example, to add two arrays a and b, you can use the following code: 

In [9]:
c = arr + brr
print(c)

[1. 1. 1.]


##4. Reshaping arrays: NumPy arrays can be reshaped using the numpy.reshape() function. This function takes an array and a new shape as input, and returns a new array with the specified shape. For example, to reshape a 1D array into a 2D array with two rows, you can use the following code: 

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6]) 
new_arr = np.reshape(arr, (2, 3))

In [11]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

##5. Indexing and slicing arrays: NumPy arrays can be indexed and sliced like lists in Python. To slice an array and extract a subset of elements, you can use the following code: 



```
a[start:end] # items start through end-1
a[start:]    # items start through the rest of the array
a[:end]      # items from the beginning through end-1
a[:]         # a copy of the whole array



a[-1]    # last item in the array
a[-2:]   # last two items in the array
a[:-2]   # everything except the last two items
# There is also the step value, which can be used with any of the above:
```



In [14]:
arr[0] #accessing 1st element
arr[1:4]

array([2, 3, 4])

In [15]:
a = np.arange(10)**3           #cube
print(a)
# array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
print(a[2])     
# 8
print(a[2:5])
# array([ 8, 27, 64])

print(a[5:])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[125 216 343 512 729]


In [17]:
a = np.arange(20) 
print(a) 
  
# a[start:stop:step] 
print(a[-8:17:2])  
  
# The : operator means all elements till the end. 
print(a[10:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 14 16]
[10 11 12 13 14 15 16 17 18 19]


In [18]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
# print(a[:, 0]) # single row with 0 index column value
# print(a[:, 1])
# print(a[:, 2])

# print(a[0, :])
# print(a[1, :])

print(a[0:2, 1:3]) # a[row, column]
print(a[0:2, 0:2])

[[2 3]
 [5 6]]
[[1 2]
 [4 5]]


In [19]:
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]]) 
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

[1 3 6]


##6. Mathematical functions: NumPy provides many mathematical functions for working with arrays, such as numpy.mean(), numpy.median(), numpy.std(), and numpy.max(). These functions can be used to calculate statistics and perform other calculations on arrays.

In [20]:
b = np.array([[1 ,2 ],
              [3 ,4 ],
              [5 ,6 ]]) 

print(b.sum(axis=0))                     # sum of each column

print(b.min(axis=1))                           # min of each row

print(b.mean(axis=1))                           # mean of each row

[ 9 12]
[1 3 5]
[1.5 3.5 5.5]


##7. Broadcasting: NumPy arrays can be broadcasted, which means that a smaller array can be used in operations with a larger array. For example, to add a scalar value to an array, you can use the following code:

In [21]:
 arr = np.array([1, 2, 3]) 
 new_arr = arr + 1
 print(new_arr)

[2 3 4]


These are just a few of the many operations that NumPy provides for working with arrays. NumPy is a very powerful library, and there are many more functions and operations that you can learn as you become more familiar with the library.
[here](https://numpy.org/)

##Why do we need NumPy? [when python lists are already there]

we cannot perform operations on all the elements of two list directly.
For example, we cannot multiply two lists directly we will have to do it element wise. 
This is where the role of NumPy comes into play.

In [22]:
list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]


print(list1*list2)

TypeError: ignored

In [23]:
# Convert list1 into a NumPy array 
a1 = np.array(list1) 
  
# Convert list2 into a NumPy array 
a2 = np.array(list2) 
  
print("Multiplication: " , a1*a2)
print("Addition: " , a1+a2)
print("Subtraction: " , a1-a2)
print("Division: " , a1/a2)
print("Modulus: " , a1%a2)


Multiplication:  [10 18 24 28 30 30]
Addition:  [11 11 11 11 11 11]
Subtraction:  [-9 -7 -5 -3 -1  1]
Division:  [0.1        0.22222222 0.375      0.57142857 0.83333333 1.2       ]
Modulus:  [1 2 3 4 5 1]


##Properties of np arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a, a.dtype, a.ndim, a.shape)

a = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(a, a.dtype, a.ndim, a.shape)

a = np.zeros((3,3))
print(a)

a = np.empty((4,4))
print(a)

b = np.ones_like(a)
print(b)

[1 2 3 4 5] int64 1 (5,)
[1. 2. 3. 4. 5.] float64 1 (5,)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2.72534831e-316 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 6.90285231e-310]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(np.linspace(0, 10, 5))  #used to create an evenly spaced sequence in a specified interval with 5 samples.
print(np.arange(0, 10, 2))

a = np.arange(6)  
print(a, "np.arange")

b = np.arange(12).reshape(4,3) 
print("np.arange(12).reshape(4,3)")
print(b)

c = np.arange(24).reshape(2,3,4)
print("np.arange(24).reshape(2,3,4)")
print(c)


b = np.arange(12).reshape(3,4)
print("np.arange(12).reshape(3,4)")
print(b)


[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]
[0 1 2 3 4 5] np.arange
np.arange(12).reshape(4,3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
np.arange(24).reshape(2,3,4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
np.arange(12).reshape(3,4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
